/**
 * Flow-diagram tests (FLOWDIAG-DOC).
 *
 * Unit half: seeds a real SQLite graph via QueryBuilder and asserts the
 * collector/renderer contracts — entry-point detection, determinism, module
 * collapse, mermaid-safe output, changed-bytes-only writes.
 * Lifecycle half: a real fixture project through initSync/indexAll/sync
 * asserts the auto-refresh gate (REQ-FLOWDIAG-002).
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { DatabaseConnection } from '../src/db';
import { QueryBuilder } from '../src/db/queries';
import {
  collectFlows,
  renderMermaidFlowchart,
  writeFlowDiagramIfChanged,
  shouldAutoRefreshDiagram,
  resolveDiagramConfig,
  generateFlowDiagram,
  DEFAULT_DIAGRAM_OPTIONS,
} from '../src/diagram/flow-diagram';
import { SpecShip } from '../src/index';
import type { Node, Edge } from '../src/types';

let dir: string;
let conn: DatabaseConnection;
let q: QueryBuilder;

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'specship-flowdiag-'));
  conn = DatabaseConnection.initialize(path.join(dir, 'test.db'));
  q = new QueryBuilder(conn.getDb());
});
afterEach(() => {
  try { conn.close(); } catch { /* ignore */ }
  try { fs.rmSync(dir, { recursive: true, force: true }); } catch { /* ignore */ }
});

function fn(id: string, filePath: string, opts: { kind?: Node['kind']; name?: string } = {}): void {
  q.insertNode({
    id,
    kind: opts.kind ?? 'function',
    name: opts.name ?? id.split(':').pop()!,
    qualifiedName: `${filePath}::${id}`,
    filePath,
    language: 'typescript',
    startLine: 1,
    endLine: 3,
    startColumn: 0,
    endColumn: 1,
    isExported: true,
    updatedAt: 1,
  } as Node);
}
function calls(source: string, target: string): void {
  q.insertEdge({ source, target, kind: 'calls' } as Edge);
}

describe('collectFlows (REQ-FLOWDIAG-001)', () => {
  it('finds entry points and follows call chains; isolated symbols stay out (A2)', () => {
    fn('main', 'src/cli.ts');
    fn('handle', 'src/core/handler.ts');
    fn('persist', 'src/db/store.ts');
    fn('lonely', 'src/util/lonely.ts'); // no calls in, no calls out
    calls('main', 'handle');
    calls('handle', 'persist');

    const flow = collectFlows(q, 6);
    expect([...flow.entryPointIds]).toEqual(['main']);
    expect([...flow.nodes.keys()].sort()).toEqual(['handle', 'main', 'persist']);
    expect(flow.edges).toHaveLength(2);
    expect(flow.nodes.has('lonely')).toBe(false);
  });

  it('treats route nodes as entry points even when called', () => {
    fn('registerRoutes', 'src/app.ts');
    fn('getUsers', 'src/routes/users.ts', { kind: 'route' });
    fn('load', 'src/db/store.ts');
    calls('registerRoutes', 'getUsers');
    calls('getUsers', 'load');

    const flow = collectFlows(q, 6);
    expect(flow.entryPointIds.has('getUsers')).toBe(true);
  });

  it('truncates chains at the depth bound', () => {
    for (let i = 0; i <= 5; i++) fn(`f${i}`, 'src/chain.ts');
    for (let i = 0; i < 5; i++) calls(`f${i}`, `f${i + 1}`);
    const flow = collectFlows(q, 2);
    expect(flow.nodes.has('f2')).toBe(true);
    expect(flow.nodes.has('f3')).toBe(false);
  });
});

describe('renderMermaidFlowchart (REQ-FLOWDIAG-003/004)', () => {
  it('emits a generated marker, a mermaid fence, and deterministic output (001.A3, 003.A1)', () => {
    fn('main', 'src/cli.ts');
    fn('handle', 'src/core/handler.ts');
    calls('main', 'handle');

    const render = () => renderMermaidFlowchart(collectFlows(q, 6), DEFAULT_DIAGRAM_OPTIONS);
    const first = render();
    expect(first.startsWith('<!-- generated by SpecShip')).toBe(true);
    expect(first).toContain('```mermaid');
    expect(first).toContain('flowchart TD');
    expect(render()).toBe(first);
  });

  it('groups nodes into per-module subgraphs and marks entry points', () => {
    fn('main', 'src/cli.ts');
    fn('handle', 'lib/handler.ts');
    calls('main', 'handle');
    const out = renderMermaidFlowchart(collectFlows(q, 6), DEFAULT_DIAGRAM_OPTIONS);
    expect(out).toContain('subgraph src["src"]');
    expect(out).toContain('subgraph lib["lib"]');
    expect(out).toContain('(["main"])'); // entry-point shape
    expect(out).toContain('["handle"]');
  });

  it('collapses modules into summary nodes over the budget (004.A1)', () => {
    fn('main', 'src/cli.ts');
    for (let i = 0; i < 30; i++) {
      fn(`w${i}`, `generated/worker${i}.ts`);
      calls('main', `w${i}`);
    }
    const out = renderMermaidFlowchart(collectFlows(q, 6), { ...DEFAULT_DIAGRAM_OPTIONS, maxNodes: 10 });
    expect(out).toContain('generated (1 flow)');
    expect(out).not.toContain('worker5');
    // collapsed module keeps a single inbound edge from main, no self loops
    const edgeLines = out.split('\n').filter((l) => /^ {2}n\d+ --> n\d+$/.test(l));
    expect(edgeLines).toHaveLength(1);
  });

  it('sanitizes labels mermaid would choke on (004.A2)', () => {
    fn('weird', 'src/w.ts', { name: 'render<T>[x]{y}|"z"' });
    fn('callee', 'src/w.ts');
    calls('weird', 'callee');
    const out = renderMermaidFlowchart(collectFlows(q, 6), DEFAULT_DIAGRAM_OPTIONS);
    expect(out).not.toMatch(/\["[^"]*[<>{}|[\]"][^"]*"\]/);
  });
});

describe('writeFlowDiagramIfChanged (REQ-FLOWDIAG-002.A3)', () => {
  it('creates, updates, and skips unchanged content without touching mtime', async () => {
    const rel = path.join('docs', 'flow-diagram.md');
    expect(writeFlowDiagramIfChanged(dir, 'one', rel)).toBe('created');
    expect(writeFlowDiagramIfChanged(dir, 'two', rel)).toBe('updated');
    const target = path.join(dir, rel);
    const mtime = fs.statSync(target).mtimeMs;
    await new Promise((r) => setTimeout(r, 20));
    expect(writeFlowDiagramIfChanged(dir, 'two', rel)).toBe('unchanged');
    expect(fs.statSync(target).mtimeMs).toBe(mtime);
  });
});

describe('config + auto-refresh gate (REQ-FLOWDIAG-002)', () => {
  it('defaults off; diagram.enabled or an existing file turns it on (002.A4)', () => {
    expect(shouldAutoRefreshDiagram(dir)).toBe(false);
    fs.writeFileSync(
      path.join(dir, 'specship.config.json'),
      JSON.stringify({ diagram: { enabled: true } }),
    );
    expect(shouldAutoRefreshDiagram(dir)).toBe(true);
    fs.rmSync(path.join(dir, 'specship.config.json'));
    fs.mkdirSync(path.join(dir, 'docs'));
    fs.writeFileSync(path.join(dir, 'docs', 'flow-diagram.md'), 'x');
    expect(shouldAutoRefreshDiagram(dir)).toBe(true);
  });

  it('resolves defaults < config < override', () => {
    fs.writeFileSync(
      path.join(dir, 'specship.config.json'),
      JSON.stringify({ diagram: { maxNodes: 42, output: 'docs/flows.md' } }),
    );
    const cfg = resolveDiagramConfig(dir, { maxNodes: 7 });
    expect(cfg.maxNodes).toBe(7);
    expect(cfg.output).toBe('docs/flows.md');
    expect(cfg.depth).toBe(DEFAULT_DIAGRAM_OPTIONS.depth);
  });

  it('generateFlowDiagram writes the file and reports counts', () => {
    fn('main', 'src/cli.ts');
    fn('handle', 'src/core.ts');
    calls('main', 'handle');
    const result = generateFlowDiagram(q, dir);
    expect(result.status).toBe('created');
    expect(fs.existsSync(path.join(dir, 'docs', 'flow-diagram.md'))).toBe(true);
    expect(result.entryPoints).toBe(1);
    expect(result.nodeCount).toBe(2);
    expect(generateFlowDiagram(q, dir).status).toBe('unchanged');
  });
});

describe('sync keeps the diagram fresh (REQ-FLOWDIAG-002 lifecycle)', () => {
  let projectDir: string;

  beforeEach(() => {
    projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'specship-flowdiag-proj-'));
    fs.mkdirSync(path.join(projectDir, 'src'));
    fs.writeFileSync(
      path.join(projectDir, 'src', 'main.ts'),
      'import { helper } from "./helper";\nexport function main() { return helper(); }\n',
    );
    fs.writeFileSync(
      path.join(projectDir, 'src', 'helper.ts'),
      'export function helper() { return 1; }\n',
    );
  });
  afterEach(() => {
    try { fs.rmSync(projectDir, { recursive: true, force: true }); } catch { /* ignore */ }
  });

  it('index/sync leave docs/ alone until opted in, then track flow changes (A1, A2, A4)', async () => {
    const cg = SpecShip.initSync(projectDir);
    try {
      await cg.indexAll();
      // A4: no diagram file, no opt-in → nothing written under docs/
      expect(fs.existsSync(path.join(projectDir, 'docs'))).toBe(false);

      // Explicit first generation creates the file.
      const created = cg.generateFlowDiagram();
      expect(created.status).toBe('created');
      const target = path.join(projectDir, 'docs', 'flow-diagram.md');
      expect(fs.readFileSync(target, 'utf-8')).toContain('main');

      // A1: a new call chain lands in the diagram on sync.
      fs.writeFileSync(
        path.join(projectDir, 'src', 'extra.ts'),
        'import { helper } from "./helper";\nexport function extraFlow() { return helper(); }\n',
      );
      await cg.sync();
      expect(fs.readFileSync(target, 'utf-8')).toContain('extraFlow');

      // A2: deleting the file removes its flow on the next sync.
      fs.rmSync(path.join(projectDir, 'src', 'extra.ts'));
      await cg.sync();
      expect(fs.readFileSync(target, 'utf-8')).not.toContain('extraFlow');
    } finally {
      cg.close();
    }
  });
});
